version: '3.3'

services:
    rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: always
      ports:
        - "15672:15672"
        - "5672:5672"
    mysql:
      image: mysql
      container_name: mysql
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
